import fs from 'node:fs';import test from 'node:test';import assert from 'node:assert/strict';
import {buildEscapeDraft} from './seed/build-escape-draft.mjs';import {buildBuyOnceDraft} from './seed/build-buy-once-draft.mjs';import {buildTodoistWorkflow} from './seed/build-todoist-workflow.mjs';import {buildAnytypeOfflineDraft} from './seed/build-anytype-offline-draft.mjs';import {escapeDefinitions,evaluateCandidate} from '../lib/discovery/escape-model.ts';
const read=p=>JSON.parse(fs.readFileSync(new URL('../'+p,import.meta.url),'utf8'));
const input=()=>buildTodoistWorkflow(buildBuyOnceDraft(buildEscapeDraft(read('.seed-output/editorial-fit/reviewed-five-ecosystems.json'),read('seed/research/escape-content-2026-10-07.json'),read('seed/research/escape-candidates-2026-10-07.json'),read('seed/research/escape-draft-review-2026-10-07.json')).reviewed,read('seed/research/escape-buy-once-review-2026-10-07.json')).bundle,read('seed/research/todoist-workflow-review-2026-10-07.json')).bundle;
const review=()=>read('seed/research/anytype-offline-review-2026-10-08.json');
test('only Anytype reviewed claims and offline route context change; three drafts qualify without publication',()=>{
 const b=input(),before=JSON.stringify(b),r=buildAnytypeOfflineDraft(b,review());assert.equal(JSON.stringify(b),before);assert.equal(r.report.qualifiedDraftCandidates,3);assert.equal(r.report.qualifiedPublishedCandidates,0);assert.equal(r.report.publishable,false);
 for(const p of b.products){const a=r.bundle.products.find(a=>a.slug===p.slug);if(p.slug!=='anytype')assert.deepEqual(a,p);else{assert.equal(a.status,'draft');assert.deepEqual(a.audiences,p.audiences);assert.deepEqual(a.problems,p.problems);for(const c of p.attributes)if(!['works-offline','pricing-model','trade-off-summary'].includes(c.slug))assert.deepEqual(a.attributes.find(a=>a.slug===c.slug),c);assert.equal(a.anchors[0].scope,'personal-offline-note-object-organization');}}
 for(const route of b.escapeRoutes){const a=r.bundle.escapeRoutes.find(a=>a.slug===route.slug);if(route.slug!=='offline-notion-alternatives')assert.deepEqual(a,route);else{assert.equal(a.status,'draft');assert.equal(a.editoriallyApproved,false);assert.ok(a.description.includes('Notion also supports offline'));assert.deepEqual(a.products.map(m=>m.productSlug),route.products.map(m=>m.productSlug));}}
 const anytype=r.pages.find(p=>p.slug==='anytype');assert.equal(evaluateCandidate(escapeDefinitions[1],{product:anytype}).eligible,false);assert.equal(evaluateCandidate(escapeDefinitions[2],{product:anytype}).eligible,false);
});
test('rejects baseline, publication, official source, scope and missing limitations drift',()=>{
 for(const mutate of [r=>r.publicationApproved=true,r=>r.scope='full-notion-parity',r=>r.beforeSha256='wrong',r=>r.sources[0].url='https://example.com/',r=>r.sources.pop(),r=>r.claims[0].value=false,r=>r.claims.pop(),r=>r.routeDescription='Notion cannot work offline',r=>r.claims.find(c=>c.slug==='trade-off-summary').value='All features supported']){const r=review();mutate(r);assert.throws(()=>buildAnytypeOfflineDraft(input(),r));}
 const b=input();b.products.find(p=>p.slug==='obsidian').status='published';assert.throws(()=>buildAnytypeOfflineDraft(b,review()));
});
test('repeat application refuses prior-claim drift rather than silently replacing reviewed records',()=>{const r=buildAnytypeOfflineDraft(input(),review());assert.throws(()=>buildAnytypeOfflineDraft(r.bundle,review()),/baseline drift/);});
